### ISSUE TITLE
runtime error re: sndio

### ISSUE THREAD

**Issue by acxz** [funilrys/aur-cava#9]
When running cava I get the following error:
```
acxz@archard ~ (git)-[master] % cava
cava: error while loading shared libraries: libsndio.so.7: cannot open shared object file: No such file or directory
127 acxz@archard ~ (git)-[master] %   
```

Package was built in chroot.

After installing `sndio`, the error does not appear and cava works properly.

```
paru -Syu sndio
```

Should `sndio` be a dep instead of an optdep? Or maybe it is somehow possible to dynamically try to load the sndio library only if sndio exists? Right now it seems that cava will try to load sndio whether it is on the system or not.

**Comment by BachoSeven** [comment]
@funilrys First of all thanks for maintaining this package!

Regarding this issue, I wanted to report that by putting `portaudio` and `sndio` in `makedepends()`, they do in fact get linked at build time, so that if I then remove them (which makes sense since it is allegedly listed in `optdepends()`) I get a runtime error:

```sh
cava: error while loading shared libraries: libportaudio.so.2: cannot open shared object file: No such file or directory
```

Thus, I think they should really either be both runtime dependencies in `depends()`, or just optional ones without being in `makedepends()` as well. I would opt for the latter option, since for instance `cava-git` doesn't even list them as dependencies at all and so they aren't strictly needed for base functionality.

**Comment by acxz** [comment]
> optional ones without being in makedepends()

This is not an option, since they are build time deps. Adding it to optdeps and not makedeps will not let cava use either dep at runtime.

**Comment by BachoSeven** [comment]
@acxz See `cava-git`: it builds without those as makedepends. Additionally, I tested removing them from makedepends on this package as well, unininstalled them and it built (and ran) just fine!

**Comment by acxz** [comment]
Sorry, I should have clarified.

they are optional build time deps. `cava` will still build just fine without them, but more support is added if cava is built with them. Howver, if cava is built with them than they must also be hard runtime deps and not optdeps.
